name: [히든페이스]Hidden Face 전체 영화 다시보기~2024-KO
description: This is an action to assign yourself to an issue for a repo you are not a contributor to.
author: Seo Moon
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs: 
  message:
    description: 'Message to prospective contributor'
    required: false
    default: ''
  issueCurrentlyAssignedMessage:
    description: 'Message to contributors if issue is already assigned'
    required: false
    default: 'The issue you are trying to assign to yourself is already assigned.'
  trigger:
    description: 'The string that triggers the action'
    required: false
    default: '.take'
  token:
    description: 'The GitHub PAT used to authenticate when updating the Issue'
    required: true
